# Generated by Django 4.0.3 on 2022-09-23 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_category_remove_auctionlist_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='category',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='auctions.category'),
            preserve_default=False,
        ),
    ]
