# Generated by Django 4.0.3 on 2022-09-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auctionlist_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='category',
            field=models.CharField(max_length=40),
        ),
    ]
