# Generated by Django 4.0.3 on 2022-09-23 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_auctionlist_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
